version: '3.1'

services:

  mysql:
    hostname: mysql
    container_name: sw_task_mysql
    image: sw/mysql
    build: 
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: swt4sks
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sw_task_rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672

  redis:
    image: redis
    container_name: fs_redis
    hostname: redis
  
  api-manager:
    hostname: api
    container_name: sw_task_api
    build:
      context: .
    image: sword-health/go
    env_file:
      .env
    networks: 
      - backend
    volumes: 
      - "../api/src:/go/src"
    ports: 
      - "8000:8000"
    command:
      - air

  notification:
    hostname: notification
    container_name: sw_task_notification
    build:
      context: .
    image: sword-health/go
    env_file:
      .env
    networks: 
      - backend
    volumes: 
      - "../notification/src:/go/src"
    command:
      - air
  
  user:
    hostname: user
    container_name: sw_task_user
    build:
      context: .
    image: sword-health/go
    env_file:
      .env
    networks: 
      - backend
    volumes: 
      - "../user/src:/go/src"
    command:
      - air
networks:
  default:
    external: true
    name: sw_task_be