version: '3.1'

services:

  mysql:
    hostname: mysql
    container_name: sword_task_mysql
    image: sw/mysql
    build: 
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: swt4sks
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sword_task_rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672

  redis:
    image: redis
    container_name: sword_task_redis
    hostname: redis
  
  api-manager:
    hostname: api
    container_name: sword_task_api
    build:
      context: ./go
    image: sword-health/go
    env_file:
      .env
    volumes: 
      - "./api/src:/go/src"
    ports: 
      - "8000:8000"
    command:
      - air
  
  task:
    hostname: task
    container_name: sword_task_task
    build:
      context: ./go
    image: sword-health/go
    env_file:
      .env
    volumes: 
      - "./task/src:/go/src"
    command:
      - air
        
  notification:
    hostname: notification
    container_name: sword_task_notification
    build:
      context: ./go
    image: sword-health/go
    env_file:
      .env
    volumes: 
      - "./notification/src:/go/src"
    command:
      - air
  
  user:
    hostname: user
    container_name: sword_task_user
    build:
      context: ./go
    image: sword-health/go
    env_file:
      .env
    volumes: 
      - "./user/src:/go/src"
    command:
      - air
      