version: '3.4'

# if you want to use this docker-compose, clone the docker repository:
# https://bitbucket.org/foursource/docker

services:
  task:
    hostname: task
    container_name: sw_task_task
    build:
      context: .
    image: sword-health/go
    env_file:
      .env
    networks: 
      - backend
    volumes: 
      - "../src:/go/src"
    command:
      - air
networks:
  backend:
    external: true
    name: sw_task_be